services:
  trader:
    container_name: container-trader
    image: prosperity/trader
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  mongodb:
    image: mongo
    container_name: container-mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb_data:/mongodb_data

volumes:
  mongodb_data:
    driver: local

networks:
  prosperity-network:
    external: true